var five = 5;
var ten = 10;
console.log("\nTest 1: Five is equal to 5?");
console.log(five == 5);
console.log("\nTest 2: ten is equal to 10?");
console.log(ten == 10);
console.log("\nTest 3: five is not equal to 10?");
console.log(five != 10);
console.log("\nTest 4: ten is greater than 5");
console.log(10 > 5);
console.log("\nTest 5: five is smaller than 10");
console.log(5 < 10);
console.log("\nTest 6: ten is smaller than 5");
console.log(10 < 5);
console.log("\nTest 7: five is equal to 10");
console.log(five == ten);
console.log("\nTest 8: ten is not equal to 10");
console.log(ten != ten);
console.log("\nTest 9: ten is greater that 11");
console.log(10 > 11);
console.log("\nTest 10: five is smaller than one");
console.log(5 < 1);
